apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-app
  name: prometheus-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: prometheus-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-app
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        resources: {}
status: {}
