apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-app
  name: prometheus-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-app
status:
  loadBalancer: {}
