apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grafana-app
  name: grafana-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: grafana-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana-app
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        resources: {}
status: {}
