apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana-app
  name: grafana-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-app
status:
  loadBalancer: {}
